# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

u = User.create!(:email=>"admin@documentor.com", :password=>"p20o20e13", :password_confirmation=>"p20o20e13")
Role.create!(:name=>"admin")
u.roles << Role.find(1)

c_type_1=ComponentType.create!(:name=>'Address')
c_type_2=ComponentType.create!(:name=>'AmtFigure')
c_type_3=ComponentType.create!(:name=>'AmtWords')
c_type_4=ComponentType.create!(:name=>'Date')
c_type_5=ComponentType.create!(:name=>'Initials')
c_type_6=ComponentType.create!(:name=>'Letterhead')
c_type_7=ComponentType.create!(:name=>'Name')
c_type_8=ComponentType.create!(:name=>'Number')
c_type_9=ComponentType.create!(:name=>'Rate')
c_type_10=ComponentType.create!(:name=>'Seal')
c_type_11=ComponentType.create!(:name=>'Signature')
c_type_12=ComponentType.create!(:name=>'Stamp')

ComponentSpec.create!(:name=>'Bank',:component_type_id=>c_type_1.id)
 ComponentSpec.create!(:name=>'Counterparty',:component_type_id=>c_type_1.id)
 ComponentSpec.create!(:name=>'Other party',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 1',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 2',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 3',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 4',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 5',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 6',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 7',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 8',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 9',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Facility 10',:component_type_id=>c_type_2.id)
 ComponentSpec.create!(:name=>'Total',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 1',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 2',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 3',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 4',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 5',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 6',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 7',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 8',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 9',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Facility 10',:component_type_id=>c_type_3.id)
 ComponentSpec.create!(:name=>'Total',:component_type_id=>c_type_4.id)
 ComponentSpec.create!(:name=>'Birth',:component_type_id=>c_type_4.id)
 ComponentSpec.create!(:name=>'Stamping',:component_type_id=>c_type_4.id)
 ComponentSpec.create!(:name=>'Sanction',:component_type_id=>c_type_4.id)
 ComponentSpec.create!(:name=>'Board Resolution',:component_type_id=>c_type_4.id)
 ComponentSpec.create!(:name=>'Acceptance',:component_type_id=>c_type_4.id)
 ComponentSpec.create!(:name=>'Execution',:component_type_id=>c_type_5.id)
 ComponentSpec.create!(:name=>'Bank',:component_type_id=>c_type_5.id)
 ComponentSpec.create!(:name=>'Counterparty',:component_type_id=>c_type_5.id)
 ComponentSpec.create!(:name=>'Other party',:component_type_id=>c_type_6.id)
 ComponentSpec.create!(:name=>'Bank',:component_type_id=>c_type_6.id)
 ComponentSpec.create!(:name=>'Chartered Accountant',:component_type_id=>c_type_6.id)
 ComponentSpec.create!(:name=>'Counterparty',:component_type_id=>c_type_6.id)
 ComponentSpec.create!(:name=>'Plain Paper',:component_type_id=>c_type_7.id)
 ComponentSpec.create!(:name=>'Bank',:component_type_id=>c_type_7.id)
 ComponentSpec.create!(:name=>'Counterparty',:component_type_id=>c_type_7.id)
 ComponentSpec.create!(:name=>'Guarantor',:component_type_id=>c_type_7.id)
 ComponentSpec.create!(:name=>'Promoter',:component_type_id=>c_type_7.id)
 ComponentSpec.create!(:name=>'Third Party',:component_type_id=>c_type_8.id)
 ComponentSpec.create!(:name=>'Reference',:component_type_id=>c_type_9.id)
 ComponentSpec.create!(:name=>'Benchmark',:component_type_id=>c_type_9.id)
 ComponentSpec.create!(:name=>'Floating',:component_type_id=>c_type_9.id)
 ComponentSpec.create!(:name=>'Fixed',:component_type_id=>c_type_9.id)
 ComponentSpec.create!(:name=>'Common',:component_type_id=>c_type_10.id)
 ComponentSpec.create!(:name=>'Hologram',:component_type_id=>c_type_10.id)
 ComponentSpec.create!(:name=>'Notarization',:component_type_id=>c_type_10.id)
 ComponentSpec.create!(:name=>'Bank',:component_type_id=>c_type_10.id)
 ComponentSpec.create!(:name=>'Chartered Accountant',:component_type_id=>c_type_10.id)
 ComponentSpec.create!(:name=>'Counterparty',:component_type_id=>c_type_10.id)
 ComponentSpec.create!(:name=>'ROC',:component_type_id=>c_type_11.id)
 ComponentSpec.create!(:name=>'Employee',:component_type_id=>c_type_11.id)
 ComponentSpec.create!(:name=>'Counterparty A',:component_type_id=>c_type_11.id)
 ComponentSpec.create!(:name=>'Counterparty B',:component_type_id=>c_type_11.id)
 ComponentSpec.create!(:name=>'Other party A',:component_type_id=>c_type_11.id)
 ComponentSpec.create!(:name=>'Other party B',:component_type_id=>c_type_11.id)
 ComponentSpec.create!(:name=>'Other party C',:component_type_id=>c_type_11.id)
 ComponentSpec.create!(:name=>'Other party D',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Revenue',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Bank',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Counterparty A',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Counterparty B',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Other party A',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Other party B',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Guarantor',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Chartered Accountant',:component_type_id=>c_type_12.id)
 ComponentSpec.create!(:name=>'Notarization',:component_type_id=>c_type_12.id)

Component.create!(:name=>'Address - Bank')
Component.create!(:name=>'Address - Counterparty')
Component.create!(:name=>'Address - Other party')
Component.create!(:name=>'AmtFigure - Facility 1')
Component.create!(:name=>'AmtFigure - Facility 2')
Component.create!(:name=>'AmtFigure - Facility 3')
Component.create!(:name=>'AmtFigure - Facility 4')
Component.create!(:name=>'AmtFigure - Facility 5')
Component.create!(:name=>'AmtFigure - Facility 6')
Component.create!(:name=>'AmtFigure - Facility 7')
Component.create!(:name=>'AmtFigure - Facility 8')
Component.create!(:name=>'AmtFigure - Facility 9')
Component.create!(:name=>'AmtFigure - Facility 10')
Component.create!(:name=>'AmtFigure - Total')
Component.create!(:name=>'AmtWords - Facility 1')
Component.create!(:name=>'AmtWords - Facility 2')
Component.create!(:name=>'AmtWords - Facility 3')
Component.create!(:name=>'AmtWords - Facility 4')
Component.create!(:name=>'AmtWords - Facility 5')
Component.create!(:name=>'AmtWords - Facility 6')
Component.create!(:name=>'AmtWords - Facility 7')
Component.create!(:name=>'AmtWords - Facility 8')
Component.create!(:name=>'AmtWords - Facility 9')
Component.create!(:name=>'AmtWords - Facility 10')
Component.create!(:name=>'AmtWords - Total')
Component.create!(:name=>'Date - Birth')
Component.create!(:name=>'Date - Stamping')
Component.create!(:name=>'Date - Sanction')
Component.create!(:name=>'Date - Board Resolution')
Component.create!(:name=>'Date - Acceptance')
Component.create!(:name=>'Date - Execution')
Component.create!(:name=>'Initials - Bank')
Component.create!(:name=>'Initials - Counterparty')
Component.create!(:name=>'Initials - Other party')
Component.create!(:name=>'Letterhead - Bank')
Component.create!(:name=>'Letterhead - Chartered Accountant')
Component.create!(:name=>'Letterhead - Counterparty')
Component.create!(:name=>'Letterhead - Plain Paper')
Component.create!(:name=>'Name - Bank')
Component.create!(:name=>'Name - Counterparty')
Component.create!(:name=>'Name - Guarantor')
Component.create!(:name=>'Name - Promoter')
Component.create!(:name=>'Name - Third Party')
Component.create!(:name=>'Number - Reference')
Component.create!(:name=>'Rate - Benchmark')
Component.create!(:name=>'Rate - Floating')
Component.create!(:name=>'Rate - Fixed')
Component.create!(:name=>'Seal - Common')
Component.create!(:name=>'Seal - Hologram')
Component.create!(:name=>'Seal - Notarization')
Component.create!(:name=>'Seal - Bank')
Component.create!(:name=>'Seal - Chartered Accountant')
Component.create!(:name=>'Seal - Counterparty')
Component.create!(:name=>'Signature - ROC')
Component.create!(:name=>'Signature - Employee')
Component.create!(:name=>'Signature - Counterparty A')
Component.create!(:name=>'Signature - Counterparty B')
Component.create!(:name=>'Signature - Other party A')
Component.create!(:name=>'Signature - Other party B')
Component.create!(:name=>'Signature - Other party C')
Component.create!(:name=>'Signature - Other party D')
Component.create!(:name=>'Stamp - Revenue')
Component.create!(:name=>'Stamp - Bank')
Component.create!(:name=>'Stamp - Counterparty A')
Component.create!(:name=>'Stamp - Counterparty B')
Component.create!(:name=>'Stamp - Other party A')
Component.create!(:name=>'Stamp - Other party B')
Component.create!(:name=>'Stamp - Guarantor')
Component.create!(:name=>'Stamp - Chartered Accountant')
Component.create!(:name=>'Stamp - Notarization')




